# -*- coding: utf-8 -*-
"""Employee Database.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IQ9R_pbg9sD4gbYwEzyaFH2KKdKVEudU
"""

import sqlite3

# Connect to the database (or create it if it doesn't exist)
conn = sqlite3.connect('employee_db.sqlite')
cursor = conn.cursor()

# Create the employees table
cursor.execute("""
CREATE TABLE IF NOT EXISTS employees (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    age INTEGER NOT NULL,
    salary REAL NOT NULL
)
""")
conn.commit()

# Function to add an employee to the database
def add_employee():
    name = input("Enter employee name: ")
    age = int(input("Enter employee age: "))
    salary = float(input("Enter employee salary : $"))

    cursor.execute("""
    INSERT INTO employees (name, age, salary)
    VALUES (?,?,?)
    """, (name, age, salary))
    conn.commit()
    print("Employee added successfully.")

# Function to view all employees in the database
def view_employees():
    cursor.execute("""
    SELECT * FROM employees
    """)
    rows = cursor.fetchall()
    print("ID\tName\tAge\tSalary")
    for row in rows:
        print(f"{row[0]}\t{row[1]}\t{row[2]}\t{row[3]}")

# Main program loop
while True:
    print("""
    1. Add Employee
    2. View Employees
    3. Quit
    """)
    choice = int(input("Enter choice: "))
    if choice == 1:
        add_employee()
    elif choice == 2:
        view_employees()
    elif choice == 3:
      print("Exit Successful")
      break